import React, {useState,useEffect} from 'react';
const KEY='gcare_owner_token';
const origin=(import.meta.env.VITE_API_URL || '').replace(/\/$/,'');
export default function OwnerPortal(){
 const [token,setToken]=useState(()=>sessionStorage.getItem(KEY)||'');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const [accounts,setAccounts]=useState<any[]>([]);const [records,setRecords]=useState<Record<string,any[]>>({});const [section,setSection]=useState('applications');const [notes,setNotes]=useState<Record<string,string>>({});const [ids,setIds]=useState<Record<string,string[]>>({});
 async function api(route:string,method='GET',body?:any){const res=await fetch(origin+'/api/owner/'+route,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined});const data=await res.json();if(!res.ok){if(res.status===401 && route!=='login'){sessionStorage.removeItem(KEY);setToken('');setAccounts([]);setRecords({});}throw Error(data.error||'Request failed');}return data;}
 async function load(){const [a,r]=await Promise.all([api('accounts'),api('records')]);setAccounts(a);setRecords(r);setIds(Object.fromEntries(a.map((u:any)=>[u.id,u.assignedElderIds||[]])));}
 useEffect(()=>{if(token)load().catch(e=>setError(e.message));},[token]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const data=await api('login','POST',{email,password});sessionStorage.setItem(KEY,data.token);setToken(data.token);setPassword('');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function review(account:any,decision:string){setBusy(true);setError('');try{await api('accounts/'+encodeURIComponent(account.id),'PUT',{decision,elderIds:ids[account.id]||[],note:notes[account.id]||''});await load();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function proof(a:any){setError('');try{const res=await fetch(origin+'/api/owner/accounts/'+encodeURIComponent(a.id)+'/proof',{headers:{Authorization:'Bearer '+token}});if(!res.ok)throw Error((await res.json()).error);const url=URL.createObjectURL(await res.blob());const link=document.createElement('a');link.href=url;link.download=a.profile.accessVerification.proofFile.fileName;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e:any){setError(e.message);}}
 const button='rounded-lg border px-4 py-2 hover:bg-muted disabled:opacity-50';
 return <main className="min-h-screen bg-background text-foreground"><div className="mx-auto max-w-6xl p-6 space-y-6"><header className="flex items-center justify-between"><div><h1 className="text-2xl font-semibold">G-Care Owner Portal</h1><p className="text-muted-foreground">Private administration and account verification</p></div>{token&&<button className={button} onClick={async()=>{try{await api('logout','POST');sessionStorage.removeItem(KEY);setToken('');setAccounts([]);setRecords({});}catch(e:any){setError(e.message);}}}>Sign out</button>}</header>
 {error&&<p role="alert" className="rounded-lg border border-destructive p-3 text-destructive">{error}</p>}
 {!token?<form onSubmit={login} className="mx-auto max-w-md rounded-xl border bg-card p-6 space-y-4"><h2 className="text-xl">Owner sign-in</h2><p className="text-sm text-muted-foreground">Owner access is configured privately. There is no public owner registration.</p><label className="block">Owner email<input type="email" required autoComplete="username" className="mt-1 w-full rounded border p-2" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="block">Password<input type="password" required autoComplete="current-password" className="mt-1 w-full rounded border p-2" value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy} className={button}>Sign in</button></form>:<>
 <nav className="flex flex-wrap gap-2">{['applications','accounts',...Object.keys(records)].map(x=><button key={x} className={button+(section===x?' bg-muted':'')} onClick={()=>setSection(x)}>{x[0].toUpperCase()+x.slice(1)} {x==='applications'?accounts.filter(a=>a.accessStatus==='pending').length:''}</button>)}<button className={button} onClick={()=>load().catch(e=>setError(e.message))}>Refresh</button></nav>
 {['applications','accounts'].includes(section)?<div className="space-y-4">{accounts.filter(a=>section==='accounts'||a.profile?.accessVerification?.status==='pending').map(a=>{const p=a.profile?.accessVerification;return <section key={a.id} className="rounded-xl border bg-card p-5 space-y-3"><h2 className="font-semibold">{a.name} · {a.role} · {a.accessStatus}</h2><p>{a.email}</p>{p?<><p>ID: {p.proofId} · Issuer: {p.issuer}</p>{p.proofReference&&<p className="break-all">Reference: {p.proofReference}</p>}{p.proofFile?<button className={button} onClick={()=>proof(a)}>Download proof: {p.proofFile.fileName}</button>:<p>No uploaded file (legacy reference request).</p>}<p className="text-sm text-muted-foreground">A file upload does not prove identity. Check the issuing organization and patient authorization before approving.</p><fieldset><legend>Assigned patients</legend>{(records.patients||[]).map(patient=><label key={patient.id} className="mr-4 inline-flex gap-2"><input type="checkbox" checked={(ids[a.id]||[]).includes(patient.id)} onChange={e=>setIds({...ids,[a.id]:e.target.checked?[...(ids[a.id]||[]),patient.id]:(ids[a.id]||[]).filter(id=>id!==patient.id)})}/>{patient.full_name}</label>)}</fieldset>{p.reviewNote&&<p>Previous review: {p.reviewNote}</p>}<label className="block">Review note (required)<textarea maxLength={1000} className="block w-full rounded border p-2" value={notes[a.id]||''} onChange={e=>setNotes({...notes,[a.id]:e.target.value})}/></label><div className="flex gap-2">{['approved','rejected','suspended'].map(d=><button key={d} disabled={busy||!notes[a.id]?.trim()||(d==='approved'&&!(ids[a.id]||[]).length)} className={button} onClick={()=>review(a,d)}>{d==='approved'?'Approve selected patients':d==='rejected'?'Reject':'Suspend'}</button>)}</div></>:<p>This legacy/demo account has no submitted verification request.</p>}</section>})}{section==='applications'&&!accounts.some(a=>a.accessStatus==='pending')&&<p>No pending applications.</p>}</div>:<section className="rounded-xl border p-4"><h2 className="text-xl mb-3">{section} records</h2><p className="text-sm text-muted-foreground mb-3">Read-only view, up to 500 records per collection. Credentials and document storage paths are excluded.</p><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{Object.keys(records[section]?.[0]||{}).map(k=><th key={k} className="p-2 text-left border-b">{k}</th>)}</tr></thead><tbody>{(records[section]||[]).map((row,i)=><tr key={i}>{Object.values(row).map((v,j)=><td key={j} className="p-2 border-b max-w-xs break-words">{typeof v==='object'?JSON.stringify(v):String(v??'')}</td>)}</tr>)}</tbody></table>{!records[section]?.length&&<p>No records.</p>}</div></section>}
 </> }</div></main>;
}
