import React, {useEffect,useRef,useState} from 'react';
import workerUrl from 'pdfjs-dist/legacy/build/pdf.worker.min.mjs?url';
export default function OwnerPdfViewer({url}:{url:string}) {
 const canvas=useRef<HTMLCanvasElement>(null);const [document,setDocument]=useState<any>(null);const [page,setPage]=useState(1);const [zoom,setZoom]=useState(1.2);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;let task:any;setLoading(true);setError('');setPage(1);setDocument(null);
 (async()=>{const pdf=await import('pdfjs-dist/legacy/build/pdf.mjs');if(!active)return;pdf.GlobalWorkerOptions.workerSrc=workerUrl;const response=await fetch(url);if(!response.ok)throw new Error('The private document could not be loaded.');const data=new Uint8Array(await response.arrayBuffer());if(!active)return;if(String.fromCharCode(...data.slice(0,5))!=='%PDF-')throw new Error('The uploaded file does not contain a PDF document.');task=pdf.getDocument({data});const result=await task.promise;if(active)setDocument(result);})().catch((e)=>{if(active){setError(e.name==='PasswordException'?'This PDF requires a password. Please upload an unlocked copy.':'Could not open this PDF: '+(e.message || 'Please try again.'));setLoading(false);}});
 return()=>{active=false;task?.destroy();};},[url]);
 useEffect(()=>{if(!document)return;let active=true;let rendering:any;setLoading(true);
 (async()=>{const pdfPage=await document.getPage(page);if(!active||!canvas.current)return;const target=canvas.current;const viewport=pdfPage.getViewport({scale:zoom});const ratio=window.devicePixelRatio||1;target.width=Math.floor(viewport.width*ratio);target.height=Math.floor(viewport.height*ratio);target.style.width=viewport.width+'px';target.style.height=viewport.height+'px';rendering=pdfPage.render({canvas:target,canvasContext:target.getContext('2d'),viewport,transform:ratio===1?undefined:[ratio,0,0,ratio,0,0]});await rendering.promise;if(active)setLoading(false);})().catch(e=>{if(active&&e.name!=='RenderingCancelledException'){setError('This page could not be displayed.');setLoading(false);}});
 return()=>{active=false;rendering?.cancel();};},[document,page,zoom]);
 return <section className="op-pdf-reader"><div className="op-pdf-tools"><button className="op-button" disabled={!document||page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} of {document?.numPages||'…'}</span><button className="op-button" disabled={!document||page>=document.numPages} onClick={()=>setPage(p=>p+1)}>Next</button><button className="op-button" disabled={zoom<=.6} aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(.6,z-.2))}>−</button><button className="op-button" disabled={zoom>=2.4} aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(2.4,z+.2))}>+</button></div><div className="op-pdf-pages">{loading&&!error&&<p role="status">Loading document…</p>}{error&&<p role="alert" className="op-error">{error}</p>}<canvas ref={canvas} aria-label={'PDF page '+page} hidden={!!error}/></div></section>;
}
